# Generated by Django 5.2.5 on 2026-08-01 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='is_special',
            field=models.BooleanField(default=False),
        ),
    ]
