# Generated by Django 5.2.5 on 2026-08-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_food_category_alter_food_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
    ]
