# Generated by Django 5.2.5 on 2026-08-02 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_food_ingredients'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100, verbose_name='نام مشتری')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='شماره تماس')),
                ('table_number', models.PositiveIntegerField(verbose_name='شماره میز')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('preparing', 'در حال آماده\u200cسازی'), ('ready', 'آماده'), ('served', 'تحویل داده شد'), ('cancelled', 'لغو شد')], default='new', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.food', verbose_name='غذا')),
            ],
        ),
    ]
