# Generated by Django 5.2.5 on 2026-08-02 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_alter_order_created_at_alter_order_customer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'جدید'), ('preparing', 'در حال آماده\u200cسازی'), ('ready', 'آماده'), ('done', 'تحویل داده شد')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='table_number',
            field=models.PositiveIntegerField(),
        ),
    ]
