# Generated by Django 5.2.5 on 2026-08-02 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_order_quantity_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
